[licenses]
version = 2
allow-osi-fsf-free = "either"

[advisories]
version = 2
ignore = [
    "RUSTSEC-2020-0071", # chrono 経由の依存で、chrono では該当 API つかってない https://github.com/chronotope/chrono/blob/main/deny.toml
    "RUSTSEC-2021-0145", # atty: dev deps
]
