name: Build default model

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    paths:
      - 'default-model/Makefile'
      - 'default-model/training-corpus/**'
      - 'default-model/dict/**'
      - 'default-model/anthy-corpus/**'
      - '.github/workflows/model.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-model-v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmarisa-dev clang libibus-1.0-dev unzip wget
    - uses: dtolnay/rust-toolchain@stable
    - name: Install resources
      run: sudo make install-resources
    - name: Build akaza-data
      run: cargo build --release -p akaza-data
    - name: Build model
      run: make -C default-model
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Evaluate model
      run: make -C default-model evaluate
    - name: Create model package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mv default-model/data akaza-default-model && tar czvf akaza-default-model.tar.gz akaza-default-model/
    - name: Upload model to release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.ref_name }} akaza-default-model.tar.gz --clobber
